export const questions: string[] = [
  "What have I been avoiding?",
  "What have I been doing well?",
  "What should I stop doing?",
  "What is my greatest source of joy?",
  "What important things am I not doing?",
  "How is my relationship with Mish?",
  "What negative patterns am I falling into?",
  "What am I most excited about?",
  "How do I feel about work?",
  "Am I doing the most important things?",
  "How am I feeling about my health?",
  "What would I like to start doing?",
  "Where am I not making appropriate tradeoffs?",
  "What advice would I give myself if I was someone else?",
  "Am I feeling organized?",
  "What are some of the sources of bad emotions?",
  "Am I having any emotional outbursts?",
  "Is there anyone that really irritates me?",
  "Am I taking good care of myself?",
  "Am I taking good care of the ones that I love?",
  "Am I doing anything shadowy?",
  "Am I happy with my body?",
  "Am I happy with my friendships?",
  "Do I feel like I'm doing good work?",
  "Am I feeling envious of anyone?",
  "Have I been feeling any violent desires or wanting to sabotage anyone?",
  "How am I feeling about my social media usage?",
  "Am I wasting a lot of time?",
  "Am I leaving unfulfilled promises?",
  "What is working well on social media?",
  "Is my ego driving me?",
  "What should I do more of?",
  "What should I do less of?",
  "Where am I being ineffective?",
  "What nice thing have I done for myself lately?",
  "What nice thing have I done for Mish lately?",
  "Have I called my parents lately?",
  "Are my affairs in order?",
  "What should I change about my fitness routine?",
  "If I continue as I am, what do I imagine my life will look like in 5 years?",
  "What is the most important thing I am focusing on?",
  "What are my blind spots about myself?",
  "Am I being deceptive in any way?",
  "What is the most important thing in my life right now?",
  "How happy am I with Mish?",
  "What would I like to change about my relationship with Mish?",
  "Am I giving Cato enough attention?",
  "How am I perceived at work?",
  "Is there anything I am doing that is holding me back at work?",
  "If I was to reduce what I do outside of work, what would I not cut?",
  "What should I be learning?",
  "What assumptions am I making about the future?",
  "What unlikely events could ruin me that I'm not prepared for?",
  "Where is my life precarious?",
  "What are my favorite parts of my routine?",
  "What purchase do I think would make my life better?",
];
